# VERSION=$(cat discordai/version.py | grep -oP '\d+\.\d+\.\d+') INIT_FILE_MOUNT=./init.sh:/main/init.sh docker compose up --build
version: '2.4'
services:
  app:
    build: .
    image: discord-ai/discordai:${VERSION}
    working_dir: /main
    environment:
      - DISCORD_TOKEN
      - OPENAI_KEY
    env_file: ./.env
    volumes:
      - ./discordai:/usr/local/lib/python3.11/site-packages/discordai
      - ${INIT_FILE_MOUNT}
    command:
      - sh
      - -c
      - |
        if [ -e init.sh ]
        then
            ./init.sh
        else
            echo "No init file found"
        fi
        discordai bot start