# VERSION=$(cat discordai/version.py | grep -oP '\d+\.\d+\.\d+') docker compose up --build
version: '2.4'
services:
  app:
    build: .
    image: discord-ai/discordai:${VERSION}
    working_dir: /main
    environment:
      - DISCORD_TOKEN
      - OPENAI_KEY
      - PYTHONUNBUFFERED=1
    env_file: ./.env
    volumes:
      - ./discordai:/usr/local/lib/python3.11/site-packages/discordai
      - ./init.sh:/main/init.sh
    command:
      - sh
      - -c
      - |
        ./init.sh
        discordai bot start