list_module_expected = [
    {"id": "dall-e-3", "created": "2023-10-31 20:46:29"},
    {"id": "whisper-1", "created": "2023-02-27 21:13:04"},
    {"id": "tts-1", "created": "2023-04-19 21:49:11"},
    {"id": "dall-e-2", "created": "2023-11-01 00:22:57"},
    {"id": "tts-1-hd-1106", "created": "2023-11-03 23:18:53"},
    {"id": "tts-1-hd", "created": "2023-11-03 21:13:35"},
    {"id": "gpt-4-turbo-2024-04-09", "created": "2024-04-08 18:41:17"},
    {"id": "gpt-4-turbo", "created": "2024-04-05 23:57:21"},
    {"id": "gpt-3.5-turbo-1106", "created": "2023-11-02 21:15:48"},
    {"id": "gpt-4-0613", "created": "2023-06-12 16:54:56"},
    {"id": "gpt-4-1106-preview", "created": "2023-11-02 20:33:26"},
    {"id": "gpt-4o-2024-05-13", "created": "2024-05-10 19:08:52"},
    {"id": "gpt-4-0125-preview", "created": "2024-01-23 19:20:12"},
    {"id": "gpt-4", "created": "2023-06-27 16:13:31"},
    {"id": "text-embedding-3-small", "created": "2024-01-22 18:43:17"},
    {"id": "gpt-4-turbo-preview", "created": "2024-01-23 19:22:57"},
    {"id": "text-embedding-3-large", "created": "2024-01-22 19:53:00"},
    {"id": "gpt-3.5-turbo-16k", "created": "2023-05-10 22:35:02"},
    {"id": "babbage-002", "created": "2023-08-21 16:16:55"},
    {"id": "gpt-3.5-turbo-0125", "created": "2024-01-23 22:19:18"},
    {"id": "tts-1-1106", "created": "2023-11-03 23:14:01"},
    {"id": "gpt-3.5-turbo", "created": "2023-02-28 18:56:42"},
    {"id": "gpt-3.5-turbo-instruct", "created": "2023-08-24 18:23:47"},
    {"id": "gpt-3.5-turbo-instruct-0914", "created": "2023-09-07 21:34:32"},
    {"id": "text-embedding-ada-002", "created": "2022-12-16 19:01:39"},
    {"id": "gpt-4o", "created": "2024-05-10 18:50:49"},
    {"id": "davinci-002", "created": "2023-08-21 16:11:41"},
    {
        "id": "davinci:ft-personal:jason-9582-2022-12-23-05-45-51",
        "created": "2022-12-23 05:45:51",
    },
    {
        "id": "davinci:ft-personal:wardell-stephen-curry-4943-2022-12-23-21-38-47",
        "created": "2022-12-23 21:38:47",
    },
    {
        "id": "davinci:ft-personal:adib-is-wat-3454-2022-12-22-21-18-56",
        "created": "2022-12-22 21:18:56",
    },
    {
        "id": "davinci:ft-personal:wardell-stephen-curry-4943-2022-12-23-01-19-18",
        "created": "2022-12-23 01:19:18",
    },
    {
        "id": "davinci:ft-personal:sleepy-0571-2022-12-23-04-17-07",
        "created": "2022-12-23 04:17:07",
    },
    {
        "id": "davinci:ft-personal:wardell-stephen-curry-4943-2022-12-23-02-35-30",
        "created": "2022-12-23 02:35:30",
    },
    {
        "id": "ft:davinci-002:personal:9211-adibiswat:9dJpFPUX:ckpt-step-250",
        "created": "2024-06-23 15:53:49",
    },
    {
        "id": "ft:davinci-002:personal:9211-adibiswat:9dJpGghp:ckpt-step-500",
        "created": "2024-06-23 15:53:50",
    },
    {
        "id": "ft:davinci-002:personal:9211-adibiswat:9dJpG8Jg",
        "created": "2024-06-23 15:53:50",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dlznHHD:ckpt-step-829",
        "created": "2024-06-24 21:58:36",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dlzoN6q:ckpt-step-1658",
        "created": "2024-06-24 21:58:36",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dlzoHLV",
        "created": "2024-06-24 21:58:36",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dOrCods:ckpt-step-500",
        "created": "2024-06-23 21:16:11",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dOrDi7H:ckpt-step-1000",
        "created": "2024-06-23 21:16:11",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dOrDhxp",
        "created": "2024-06-23 21:16:11",
    },
    {
        "id": "ft:babbage-002:personal:1061-adibiswat:9dGjKTat:ckpt-step-77",
        "created": "2024-06-23 12:35:30",
    },
    {
        "id": "ft:babbage-002:personal:1061-adibiswat:9dGjKNZ7:ckpt-step-154",
        "created": "2024-06-23 12:35:30",
    },
    {
        "id": "ft:babbage-002:personal:1061-adibiswat:9dGjKP3k",
        "created": "2024-06-23 12:35:31",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dQJkKSS:ckpt-step-77",
        "created": "2024-06-23 22:49:44",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dQJl3tf:ckpt-step-154",
        "created": "2024-06-23 22:49:45",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dQJlxbs",
        "created": "2024-06-23 22:49:45",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dHHH3k0:ckpt-step-77",
        "created": "2024-06-23 13:10:35",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dHHHpWC:ckpt-step-154",
        "created": "2024-06-23 13:10:35",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dHHHkJJ",
        "created": "2024-06-23 13:10:36",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-theeven:9dqzc0rv:ckpt-step-500",
        "created": "2024-06-25 03:18:44",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-theeven:9dqzcebU:ckpt-step-1000",
        "created": "2024-06-25 03:18:44",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-theeven:9dqzcdCl",
        "created": "2024-06-25 03:18:45",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1061-adibiswat:9dIC5lu0:ckpt-step-50",
        "created": "2024-06-23 14:09:17",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1061-adibiswat:9dIC5Ei3:ckpt-step-100",
        "created": "2024-06-23 14:09:17",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1061-adibiswat:9dIC5Ff3",
        "created": "2024-06-23 14:09:18",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:9211-adibiswat:9dIs09Me:ckpt-step-250",
        "created": "2024-06-23 14:52:36",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:9211-adibiswat:9dIs0reu:ckpt-step-500",
        "created": "2024-06-23 14:52:37",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:9211-adibiswat:9dIs1T5H",
        "created": "2024-06-23 14:52:37",
    },
    {
        "id": "ft:davinci-002:personal:1663-adibiswat:9dNz5DHO:ckpt-step-500",
        "created": "2024-06-23 20:20:15",
    },
    {
        "id": "ft:davinci-002:personal:1663-adibiswat:9dNz5gky:ckpt-step-1000",
        "created": "2024-06-23 20:20:15",
    },
    {
        "id": "ft:davinci-002:personal:1663-adibiswat:9dNz5aHx",
        "created": "2024-06-23 20:20:15",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jdjmZGJ:ckpt-step-500",
        "created": "2024-07-11 02:22:18",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jdjm2MV:ckpt-step-1000",
        "created": "2024-07-11 02:22:19",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jdjnzD7",
        "created": "2024-07-11 02:22:19",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jgCoeW1:ckpt-step-500",
        "created": "2024-07-11 05:00:26",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jgCoQRP:ckpt-step-1000",
        "created": "2024-07-11 05:00:26",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jgCpXW5",
        "created": "2024-07-11 05:00:27",
    },
]

list_module_expected_full = [
    {
        "id": "dall-e-3",
        "created": "2023-10-31 20:46:29",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "whisper-1",
        "created": "2023-02-27 21:13:04",
        "object": "model",
        "owned_by": "openai-internal",
    },
    {
        "id": "tts-1",
        "created": "2023-04-19 21:49:11",
        "object": "model",
        "owned_by": "openai-internal",
    },
    {
        "id": "dall-e-2",
        "created": "2023-11-01 00:22:57",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "tts-1-hd-1106",
        "created": "2023-11-03 23:18:53",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "tts-1-hd",
        "created": "2023-11-03 21:13:35",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-4-turbo-2024-04-09",
        "created": "2024-04-08 18:41:17",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-4-turbo",
        "created": "2024-04-05 23:57:21",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-3.5-turbo-1106",
        "created": "2023-11-02 21:15:48",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-4-0613",
        "created": "2023-06-12 16:54:56",
        "object": "model",
        "owned_by": "openai",
    },
    {
        "id": "gpt-4-1106-preview",
        "created": "2023-11-02 20:33:26",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-4o-2024-05-13",
        "created": "2024-05-10 19:08:52",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-4-0125-preview",
        "created": "2024-01-23 19:20:12",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-4",
        "created": "2023-06-27 16:13:31",
        "object": "model",
        "owned_by": "openai",
    },
    {
        "id": "text-embedding-3-small",
        "created": "2024-01-22 18:43:17",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-4-turbo-preview",
        "created": "2024-01-23 19:22:57",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "text-embedding-3-large",
        "created": "2024-01-22 19:53:00",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-3.5-turbo-16k",
        "created": "2023-05-10 22:35:02",
        "object": "model",
        "owned_by": "openai-internal",
    },
    {
        "id": "babbage-002",
        "created": "2023-08-21 16:16:55",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-3.5-turbo-0125",
        "created": "2024-01-23 22:19:18",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "tts-1-1106",
        "created": "2023-11-03 23:14:01",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-3.5-turbo",
        "created": "2023-02-28 18:56:42",
        "object": "model",
        "owned_by": "openai",
    },
    {
        "id": "gpt-3.5-turbo-instruct",
        "created": "2023-08-24 18:23:47",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "gpt-3.5-turbo-instruct-0914",
        "created": "2023-09-07 21:34:32",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "text-embedding-ada-002",
        "created": "2022-12-16 19:01:39",
        "object": "model",
        "owned_by": "openai-internal",
    },
    {
        "id": "gpt-4o",
        "created": "2024-05-10 18:50:49",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "davinci-002",
        "created": "2023-08-21 16:11:41",
        "object": "model",
        "owned_by": "system",
    },
    {
        "id": "davinci:ft-personal:jason-9582-2022-12-23-05-45-51",
        "created": "2022-12-23 05:45:51",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "davinci:ft-personal:wardell-stephen-curry-4943-2022-12-23-21-38-47",
        "created": "2022-12-23 21:38:47",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "davinci:ft-personal:adib-is-wat-3454-2022-12-22-21-18-56",
        "created": "2022-12-22 21:18:56",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "davinci:ft-personal:wardell-stephen-curry-4943-2022-12-23-01-19-18",
        "created": "2022-12-23 01:19:18",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "davinci:ft-personal:sleepy-0571-2022-12-23-04-17-07",
        "created": "2022-12-23 04:17:07",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "davinci:ft-personal:wardell-stephen-curry-4943-2022-12-23-02-35-30",
        "created": "2022-12-23 02:35:30",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:9211-adibiswat:9dJpFPUX:ckpt-step-250",
        "created": "2024-06-23 15:53:49",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:9211-adibiswat:9dJpGghp:ckpt-step-500",
        "created": "2024-06-23 15:53:50",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:9211-adibiswat:9dJpG8Jg",
        "created": "2024-06-23 15:53:50",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dlznHHD:ckpt-step-829",
        "created": "2024-06-24 21:58:36",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dlzoN6q:ckpt-step-1658",
        "created": "2024-06-24 21:58:36",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dlzoHLV",
        "created": "2024-06-24 21:58:36",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dOrCods:ckpt-step-500",
        "created": "2024-06-23 21:16:11",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dOrDi7H:ckpt-step-1000",
        "created": "2024-06-23 21:16:11",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dOrDhxp",
        "created": "2024-06-23 21:16:11",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:babbage-002:personal:1061-adibiswat:9dGjKTat:ckpt-step-77",
        "created": "2024-06-23 12:35:30",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:babbage-002:personal:1061-adibiswat:9dGjKNZ7:ckpt-step-154",
        "created": "2024-06-23 12:35:30",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:babbage-002:personal:1061-adibiswat:9dGjKP3k",
        "created": "2024-06-23 12:35:31",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dQJkKSS:ckpt-step-77",
        "created": "2024-06-23 22:49:44",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dQJl3tf:ckpt-step-154",
        "created": "2024-06-23 22:49:45",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dQJlxbs",
        "created": "2024-06-23 22:49:45",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dHHH3k0:ckpt-step-77",
        "created": "2024-06-23 13:10:35",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dHHHpWC:ckpt-step-154",
        "created": "2024-06-23 13:10:35",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1061-adibiswat:9dHHHkJJ",
        "created": "2024-06-23 13:10:36",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-theeven:9dqzc0rv:ckpt-step-500",
        "created": "2024-06-25 03:18:44",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-theeven:9dqzcebU:ckpt-step-1000",
        "created": "2024-06-25 03:18:44",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1663-theeven:9dqzcdCl",
        "created": "2024-06-25 03:18:45",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1061-adibiswat:9dIC5lu0:ckpt-step-50",
        "created": "2024-06-23 14:09:17",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1061-adibiswat:9dIC5Ei3:ckpt-step-100",
        "created": "2024-06-23 14:09:17",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:1061-adibiswat:9dIC5Ff3",
        "created": "2024-06-23 14:09:18",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:9211-adibiswat:9dIs09Me:ckpt-step-250",
        "created": "2024-06-23 14:52:36",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:9211-adibiswat:9dIs0reu:ckpt-step-500",
        "created": "2024-06-23 14:52:37",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:gpt-3.5-turbo-0125:personal:9211-adibiswat:9dIs1T5H",
        "created": "2024-06-23 14:52:37",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-adibiswat:9dNz5DHO:ckpt-step-500",
        "created": "2024-06-23 20:20:15",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-adibiswat:9dNz5gky:ckpt-step-1000",
        "created": "2024-06-23 20:20:15",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-adibiswat:9dNz5aHx",
        "created": "2024-06-23 20:20:15",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jdjmZGJ:ckpt-step-500",
        "created": "2024-07-11 02:22:18",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jdjm2MV:ckpt-step-1000",
        "created": "2024-07-11 02:22:19",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jdjnzD7",
        "created": "2024-07-11 02:22:19",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jgCoeW1:ckpt-step-500",
        "created": "2024-07-11 05:00:26",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jgCoQRP:ckpt-step-1000",
        "created": "2024-07-11 05:00:26",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
    {
        "id": "ft:davinci-002:personal:1663-wardellstephe:9jgCpXW5",
        "created": "2024-07-11 05:00:27",
        "object": "model",
        "owned_by": "user-ygljrfw1bneby79ndybpnodl",
    },
]

list_job_expected = [
    {
        "id": "ftjob-PJ6OUUoontOdeUlGmNDBvnfx",
        "model": "davinci-002",
        "status": "succeeded",
        "created_at": "2024-07-11 04:48:11",
        "finished_at": "2024-07-11 05:00:25",
    },
    {
        "id": "ftjob-uDSOyvIAufHM2lNZStHFkdhA",
        "model": "davinci-002",
        "status": "failed",
        "created_at": "2024-07-11 04:41:52",
        "finished_at": None,
    },
    {
        "id": "ftjob-UeuVjiLh9tJMgidlRSen48Z8",
        "model": "davinci-002",
        "status": "failed",
        "created_at": "2024-07-11 04:14:23",
        "finished_at": None,
    },
    {
        "id": "ftjob-ESLdeisl9n7rzgmi78fv7hYS",
        "model": "davinci-002",
        "status": "failed",
        "created_at": "2024-07-11 04:11:14",
        "finished_at": None,
    },
    {
        "id": "ftjob-CKyMZ8NMvYKhoAvVkQXj2pox",
        "model": "davinci-002",
        "status": "failed",
        "created_at": "2024-07-11 03:53:39",
        "finished_at": None,
    },
    {
        "id": "ftjob-IZ98fyDybi5ZLX0i0uMk140k",
        "model": "davinci-002",
        "status": "succeeded",
        "created_at": "2024-07-11 02:10:14",
        "finished_at": "2024-07-11 02:22:17",
    },
    {
        "id": "ftjob-Lz3RrqLkMcWIlC8RvGb8LDMH",
        "model": "babbage-002",
        "status": "failed",
        "created_at": "2024-06-30 03:05:05",
        "finished_at": None,
    },
    {
        "id": "ftjob-vLkvb4fnkLPeQY9fsAbJWw3v",
        "model": "babbage-002",
        "status": "failed",
        "created_at": "2024-06-30 02:59:24",
        "finished_at": None,
    },
    {
        "id": "ftjob-nz1rOfhBkm7V2SOaT9Yc20Mm",
        "model": "babbage-002",
        "status": "failed",
        "created_at": "2024-06-30 02:59:09",
        "finished_at": None,
    },
    {
        "id": "ftjob-cwMrNf7A6O7TbWQOaB02RPoG",
        "model": "babbage-002",
        "status": "failed",
        "created_at": "2024-06-28 20:25:23",
        "finished_at": None,
    },
    {
        "id": "ftjob-HuQCffXbmsNugDgDvUz3Neii",
        "model": "gpt-3.5-turbo-0125",
        "status": "succeeded",
        "created_at": "2024-06-25 02:28:39",
        "finished_at": "2024-06-25 03:18:43",
    },
    {
        "id": "ftjob-ApcqPdRqBp0qCUF70J1fa2Y3",
        "model": "gpt-3.5-turbo-0125",
        "status": "cancelled",
        "created_at": "2024-06-25 02:26:00",
        "finished_at": None,
    },
    {
        "id": "ftjob-ywdWdoR8sGwSOOjJHr0PhxGt",
        "model": "gpt-3.5-turbo-0125",
        "status": "failed",
        "created_at": "2024-06-25 02:09:32",
        "finished_at": None,
    },
    {
        "id": "ftjob-vaISvtQ6t2KHST9qUxfvJn5V",
        "model": "gpt-3.5-turbo-0125",
        "status": "cancelled",
        "created_at": "2024-06-25 02:07:04",
        "finished_at": None,
    },
    {
        "id": "ftjob-pgdOVmnKgOqpidKTfs2rUt2S",
        "model": "gpt-3.5-turbo-0125",
        "status": "failed",
        "created_at": "2024-06-25 01:59:19",
        "finished_at": None,
    },
    {
        "id": "ftjob-CJFBVbQwDKg9IsVHT88fV9up",
        "model": "gpt-3.5-turbo-0125",
        "status": "failed",
        "created_at": "2024-06-25 01:20:23",
        "finished_at": None,
    },
    {
        "id": "ftjob-WAA327cwCTThzar0nIMaOWoh",
        "model": "gpt-3.5-turbo-0125",
        "status": "failed",
        "created_at": "2024-06-24 22:13:56",
        "finished_at": None,
    },
    {
        "id": "ftjob-Ftbu3BIP6p0t4I0jbr9MWqaE",
        "model": "gpt-3.5-turbo-0125",
        "status": "succeeded",
        "created_at": "2024-06-24 20:15:56",
        "finished_at": "2024-06-24 21:58:34",
    },
    {
        "id": "ftjob-qjgkXD2s8xPNhwJpyKGLPT1J",
        "model": "davinci-002",
        "status": "succeeded",
        "created_at": "2024-06-23 22:46:25",
        "finished_at": "2024-06-23 22:49:44",
    },
    {
        "id": "ftjob-WMnwxBtBuJQgiX3ZRnuXlTF3",
        "model": "gpt-3.5-turbo-0125",
        "status": "succeeded",
        "created_at": "2024-06-23 20:31:21",
        "finished_at": "2024-06-23 21:16:09",
    },
]

list_job_expected_full = [
    {
        "id": "ftjob-PJ6OUUoontOdeUlGmNDBvnfx",
        "created_at": "2024-07-11 04:48:11",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": "ft:davinci-002:personal:1663-wardellstephe:9jgCpXW5",
        "finished_at": "2024-07-11 05:00:25",
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 12,
            "learning_rate_multiplier": 16,
        },
        "model": "davinci-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": ["file-6lbBcuvzucziSEHW8NcotY9s"],
        "seed": 535355915,
        "status": "succeeded",
        "trained_tokens": 344496,
        "training_file": "file-xmojeaTM0FANBiaFKM2CHtUF",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-uDSOyvIAufHM2lNZStHFkdhA",
        "created_at": "2024-07-11 04:41:52",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. Invalid file format. Example 2 requires at least one prompt token.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "davinci-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 1542658139,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-jWnBFHtkPVX6bgueZmpCZwV2",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-UeuVjiLh9tJMgidlRSen48Z8",
        "created_at": "2024-07-11 04:14:23",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. Expected file to have JSONL format, where every line is a valid JSON dictionary. Line 1 is not a dictionary.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "davinci-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 1572776043,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-2fzORPC0k4nT46TJmOgn4Mtm",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-ESLdeisl9n7rzgmi78fv7hYS",
        "created_at": "2024-07-11 04:11:14",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. Expected file to have JSONL format, where every line is a valid JSON dictionary. Line 1 is not a dictionary.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "davinci-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 1187322511,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-kOEdIIFQrPl8gHURBAEcE7fS",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-CKyMZ8NMvYKhoAvVkQXj2pox",
        "created_at": "2024-07-11 03:53:39",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. Invalid file format. Example 1 requires at least one prompt token.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "davinci-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 126924705,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-IIy15ygklPbvGPBmp5gu4xJl",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-IZ98fyDybi5ZLX0i0uMk140k",
        "created_at": "2024-07-11 02:10:14",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": "ft:davinci-002:personal:1663-wardellstephe:9jdjnzD7",
        "finished_at": "2024-07-11 02:22:17",
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 16,
        },
        "model": "davinci-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": ["file-uFfwxYxxjiqWoKjip83arEkz"],
        "seed": 753750607,
        "status": "succeeded",
        "trained_tokens": 148215,
        "training_file": "file-Kj10Y3HS7PTXHgE9hr5UdCug",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-Lz3RrqLkMcWIlC8RvGb8LDMH",
        "created_at": "2024-06-30 03:05:05",
        "error": {
            "code": "invalid_n_examples",
            "message": "Training file has 6 example(s), but must have at least 10 examples",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "babbage-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 1880584560,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-Kh36GpHZqXYmPhoYZ45KNujR",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1255_adibiswat",
    },
    {
        "id": "ftjob-vLkvb4fnkLPeQY9fsAbJWw3v",
        "created_at": "2024-06-30 02:59:24",
        "error": {
            "code": "invalid_n_examples",
            "message": "Training file has 6 example(s), but must have at least 10 examples",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "babbage-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 1091736885,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-exCeIJv2sDHs9dPlDl2b2ZJI",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1255_adibiswat",
    },
    {
        "id": "ftjob-nz1rOfhBkm7V2SOaT9Yc20Mm",
        "created_at": "2024-06-30 02:59:09",
        "error": {
            "code": "invalid_n_examples",
            "message": "Training file has 6 example(s), but must have at least 10 examples",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "babbage-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 425448031,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-l4KSCU80JqBl8xwayGIVQVxB",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1255_adibiswat",
    },
    {
        "id": "ftjob-cwMrNf7A6O7TbWQOaB02RPoG",
        "created_at": "2024-06-28 20:25:23",
        "error": {
            "code": "invalid_n_examples",
            "message": "Training file has 8 example(s), but must have at least 10 examples",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": "auto",
            "batch_size": "auto",
            "learning_rate_multiplier": "auto",
        },
        "model": "babbage-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 778191920,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-ReCiUOw4h4e7ETBGcNqofxN9",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1255_adibiswat",
    },
    {
        "id": "ftjob-HuQCffXbmsNugDgDvUz3Neii",
        "created_at": "2024-06-25 02:28:39",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": "ft:gpt-3.5-turbo-0125:personal:1663-theeven:9dqzcdCl",
        "finished_at": "2024-06-25 03:18:43",
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": ["file-0aylNn5VCawYtHzX3aqVg93u"],
        "seed": 1819970406,
        "status": "succeeded",
        "trained_tokens": 401901,
        "training_file": "file-JFcT9FmQ6J1nxNHJDzrs2ter",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_theeven",
    },
    {
        "id": "ftjob-ApcqPdRqBp0qCUF70J1fa2Y3",
        "created_at": "2024-06-25 02:26:00",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 11659887,
        "status": "cancelled",
        "trained_tokens": None,
        "training_file": "file-rwEBd0b16mqtGqoD8xJZufzD",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_theeven",
    },
    {
        "id": "ftjob-ywdWdoR8sGwSOOjJHr0PhxGt",
        "created_at": "2024-06-25 02:09:32",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. This training file was blocked because too many examples were flagged by our moderation API for containing content that violates OpenAI's usage policies in the following categories: hate. Use the free OpenAI Moderation API to identify these examples and remove them from your training data. See https://platform.openai.com/docs/guides/moderation for more information.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 260500084,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-4Djy7r2PJGtZguthNXKnImFO",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-vaISvtQ6t2KHST9qUxfvJn5V",
        "created_at": "2024-06-25 02:07:04",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 1571260890,
        "status": "cancelled",
        "trained_tokens": None,
        "training_file": "file-tWPJR4J3Puw7JSUC5pTbSyyA",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-pgdOVmnKgOqpidKTfs2rUt2S",
        "created_at": "2024-06-25 01:59:19",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. This training file was blocked because too many examples were flagged by our moderation API for containing content that violates OpenAI's usage policies in the following categories: hate. Use the free OpenAI Moderation API to identify these examples and remove them from your training data. See https://platform.openai.com/docs/guides/moderation for more information.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 954703414,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-wLoF45RGWC64GEGnpcjXikVg",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-CJFBVbQwDKg9IsVHT88fV9up",
        "created_at": "2024-06-25 01:20:23",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. This training file was blocked because too many examples were flagged by our moderation API for containing content that violates OpenAI's usage policies in the following categories: hate. Use the free OpenAI Moderation API to identify these examples and remove them from your training data. See https://platform.openai.com/docs/guides/moderation for more information.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 2074416376,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-Hgv0qtav04pPfFiKzsGkuHNd",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-WAA327cwCTThzar0nIMaOWoh",
        "created_at": "2024-06-24 22:13:56",
        "error": {
            "code": "invalid_training_file",
            "message": "The job failed due to an invalid training file. This training file was blocked because too many examples were flagged by our moderation API for containing content that violates OpenAI's usage policies in the following categories: hate. Use the free OpenAI Moderation API to identify these examples and remove them from your training data. See https://platform.openai.com/docs/guides/moderation for more information.",
            "param": "training_file",
        },
        "fine_tuned_model": None,
        "finished_at": None,
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 4,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": [],
        "seed": 73532835,
        "status": "failed",
        "trained_tokens": None,
        "training_file": "file-SnSbUPQwTIoLkDVE2MaGMcO8",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_wardellstephe",
    },
    {
        "id": "ftjob-Ftbu3BIP6p0t4I0jbr9MWqaE",
        "created_at": "2024-06-24 20:15:56",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dlzoHLV",
        "finished_at": "2024-06-24 21:58:34",
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 1,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": ["file-L16eJpZsQftWCSDfsZ9Jycdj"],
        "seed": 1936033663,
        "status": "succeeded",
        "trained_tokens": 206463,
        "training_file": "file-404ij5BOlCE5hcw3eED7nQ98",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_adibiswat",
    },
    {
        "id": "ftjob-qjgkXD2s8xPNhwJpyKGLPT1J",
        "created_at": "2024-06-23 22:46:25",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": "ft:davinci-002:personal:1061-adibiswat:9dQJlxbs",
        "finished_at": "2024-06-23 22:49:44",
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 1,
            "learning_rate_multiplier": 16,
        },
        "model": "davinci-002",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": ["file-T6e1WESU6g1pgSHm52uDwt3t"],
        "seed": 1057316496,
        "status": "succeeded",
        "trained_tokens": 9060,
        "training_file": "file-xNdlpV4YDqazMKucF8A7e1Fx",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1061_adibiswat",
    },
    {
        "id": "ftjob-WMnwxBtBuJQgiX3ZRnuXlTF3",
        "created_at": "2024-06-23 20:31:21",
        "error": {"code": None, "message": None, "param": None},
        "fine_tuned_model": "ft:gpt-3.5-turbo-0125:personal:1663-adibiswat:9dOrDhxp",
        "finished_at": "2024-06-23 21:16:09",
        "hyperparameters": {
            "n_epochs": 3,
            "batch_size": 1,
            "learning_rate_multiplier": 2,
        },
        "model": "gpt-3.5-turbo-0125",
        "object": "fine_tuning.job",
        "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
        "result_files": ["file-8ya7wn36JZz6cc9tEy3diyE3"],
        "seed": 1834725185,
        "status": "succeeded",
        "trained_tokens": 76449,
        "training_file": "file-RhHsfdxIq0v1AnstxhULFSvO",
        "validation_file": None,
        "estimated_finish": None,
        "integrations": [],
        "user_provided_suffix": "1663_adibiswat",
    },
]

job_info_expected = {
    "id": "ftjob-i2IyeV2xbLCSrYq45kTKSdwE",
    "created_at": "2024-06-22 22:59:37",
    "error": {"code": None, "message": None, "param": None},
    "fine_tuned_model": None,
    "finished_at": None,
    "hyperparameters": {
        "n_epochs": "auto",
        "batch_size": "auto",
        "learning_rate_multiplier": "auto",
    },
    "model": "babbage-002",
    "object": "fine_tuning.job",
    "organization_id": "org-UN3Y7fSoTFPVCWR6f4AMWsVf",
    "result_files": [],
    "seed": 652640760,
    "status": "cancelled",
    "trained_tokens": None,
    "training_file": "file-V9eC4sqGAcddWltfUg3T5gp0",
    "validation_file": None,
    "estimated_finish": None,
    "integrations": [],
    "user_provided_suffix": "107264815957200091",
}

job_events_expected = [
    {
        "id": "ftevent-XxSL9f92I9VmlWnNZnpMdodN",
        "created_at": "2024-06-22 22:59:37",
        "level": "info",
        "message": "Validating training file: file-V9eC4sqGAcddWltfUg3T5gp0",
        "object": "fine_tuning.job.event",
        "data": {},
        "type": "message",
    },
    {
        "id": "ftevent-I1m3M93vXa0NVVok5ZN7Ix4b",
        "created_at": "2024-06-22 22:59:37",
        "level": "info",
        "message": "Created fine-tuning job: ftjob-i2IyeV2xbLCSrYq45kTKSdwE",
        "object": "fine_tuning.job.event",
        "data": {},
        "type": "message",
    },
]

job_cancel_expected = {
    "result": "Canceled fine-tuning job: ftjob-i2IyeV2xbLCSrYq45kTKSdwE"
}

delete_model_expected = {
    "error": "You have insufficient permissions for this operation. Missing scopes: api.delete"
}

channel_logs_expected = {
    "guild": {
        "id": "194921511130365952",
        "name": "tstuff",
        "iconUrl": "https://cdn.discordapp.com/embed/avatars/0.png",
    },
    "channel": {
        "id": "1255993340218839111",
        "type": "GuildTextChat",
        "categoryId": None,
        "category": None,
        "name": "discordai-tests",
        "topic": None,
    },
    "dateRange": {"after": None, "before": None},
    "messages": [
        {
            "id": "1256404277124006038",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:02.529+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "this",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404278772498494",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:02.922+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "is",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404280743821333",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:03.392+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "a",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404294509265009",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:06.674+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "test channel",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404405335363750",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:33.097+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "to run",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404411689730078",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:34.612+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "discord",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404429205409873",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:38.788+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "ai tests",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404441095999580",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:41.623+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "i",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404442769653810",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:42.022+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "am",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404447966269510",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:43.261+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "writing",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404482363887676",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:51.462+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "pretermined messages",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404492522492046",
            "type": "Default",
            "timestamp": "2024-06-29T00:22:53.884+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "for the test data",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404608213844040",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:21.467+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "this",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404612135649348",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:22.402+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "is",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404615558332547",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:23.218+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "another",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404619056381963",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:24.052+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "message",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404664253943848",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:34.828+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "this",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404665923276840",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:35.226+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "is",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404668867674112",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:35.928+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "also",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404670209851392",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:36.248+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "a",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404675545006172",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:37.52+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "message",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404729156603984",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:50.302+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "here is",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404744382185502",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:53.932+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "one more",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404758667722913",
            "type": "Default",
            "timestamp": "2024-06-29T00:23:57.338+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "message",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404815299215461",
            "type": "Default",
            "timestamp": "2024-06-29T00:24:10.84+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "this is",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
        {
            "id": "1256404832739135508",
            "type": "Default",
            "timestamp": "2024-06-29T00:24:14.998+00:00",
            "timestampEdited": None,
            "callEndedTimestamp": None,
            "isPinned": False,
            "content": "the last message",
            "author": {
                "id": "194920021099675648",
                "name": "adibiswat",
                "discriminator": "0000",
                "nickname": "adib is wat",
                "color": None,
                "isBot": False,
                "roles": [],
                "avatarUrl": "https://cdn.discordapp.com/avatars/194920021099675648/2a8363435dc61fbe654cd066e198e68e.png?size=512",
            },
            "attachments": [],
            "embeds": [],
            "stickers": [],
            "reactions": [],
            "mentions": [],
        },
    ],
    "messageCount": 26,
}

parse_logs_expected_all = [
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " test channel."},
    {"prompt": "adibiswat says:", "completion": " to run."},
    {"prompt": "adibiswat says:", "completion": " discord."},
    {"prompt": "adibiswat says:", "completion": " ai tests."},
    {"prompt": "adibiswat says:", "completion": " i."},
    {"prompt": "adibiswat says:", "completion": " am."},
    {"prompt": "adibiswat says:", "completion": " writing."},
    {"prompt": "adibiswat says:", "completion": " pretermined messages."},
    {"prompt": "adibiswat says:", "completion": " for the test data."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " another."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " also."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " here is."},
    {"prompt": "adibiswat says:", "completion": " one more."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " this is."},
    {"prompt": "adibiswat says:", "completion": " the last message."},
]

parse_logs_expected_two_secs = [
    {"prompt": "adibiswat says:", "completion": " this is a."},
    {"prompt": "adibiswat says:", "completion": " test channel."},
    {"prompt": "adibiswat says:", "completion": " to run discord."},
    {"prompt": "adibiswat says:", "completion": " ai tests."},
    {"prompt": "adibiswat says:", "completion": " i am writing."},
    {"prompt": "adibiswat says:", "completion": " pretermined messages."},
    {"prompt": "adibiswat says:", "completion": " for the test data."},
    {"prompt": "adibiswat says:", "completion": " this is another message."},
    {"prompt": "adibiswat says:", "completion": " this is also a message."},
    {"prompt": "adibiswat says:", "completion": " here is."},
    {"prompt": "adibiswat says:", "completion": " one more."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " this is."},
    {"prompt": "adibiswat says:", "completion": " the last message."},
]

parse_logs_expected_five_secs = [
    {"prompt": "adibiswat says:", "completion": " this is a test channel."},
    {
        "prompt": "adibiswat says:",
        "completion": " to run discord ai tests i am writing.",
    },
    {
        "prompt": "adibiswat says:",
        "completion": " pretermined messages for the test data.",
    },
    {"prompt": "adibiswat says:", "completion": " this is another message."},
    {"prompt": "adibiswat says:", "completion": " this is also a message."},
    {"prompt": "adibiswat says:", "completion": " here is one more message."},
    {"prompt": "adibiswat says:", "completion": " this is the last message."},
]

gen_dataset_first_10_lines = [
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " test channel."},
    {"prompt": "adibiswat says:", "completion": " to run."},
    {"prompt": "adibiswat says:", "completion": " discord."},
    {"prompt": "adibiswat says:", "completion": " ai tests."},
    {"prompt": "adibiswat says:", "completion": " i."},
    {"prompt": "adibiswat says:", "completion": " am."},
    {"prompt": "adibiswat says:", "completion": " writing."},
]

gen_dataset_reverse = [
    {"prompt": "adibiswat says:", "completion": " the last message."},
    {"prompt": "adibiswat says:", "completion": " this is."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " one more."},
    {"prompt": "adibiswat says:", "completion": " here is."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " also."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " another."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " for the test data."},
    {"prompt": "adibiswat says:", "completion": " pretermined messages."},
    {"prompt": "adibiswat says:", "completion": " writing."},
    {"prompt": "adibiswat says:", "completion": " am."},
    {"prompt": "adibiswat says:", "completion": " i."},
    {"prompt": "adibiswat says:", "completion": " ai tests."},
    {"prompt": "adibiswat says:", "completion": " discord."},
    {"prompt": "adibiswat says:", "completion": " to run."},
    {"prompt": "adibiswat says:", "completion": " test channel."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " this."},
]

gen_dataset_offset_1 = [
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " test channel."},
    {"prompt": "adibiswat says:", "completion": " to run."},
    {"prompt": "adibiswat says:", "completion": " discord."},
    {"prompt": "adibiswat says:", "completion": " ai tests."},
    {"prompt": "adibiswat says:", "completion": " i."},
    {"prompt": "adibiswat says:", "completion": " am."},
    {"prompt": "adibiswat says:", "completion": " writing."},
    {"prompt": "adibiswat says:", "completion": " pretermined messages."},
    {"prompt": "adibiswat says:", "completion": " for the test data."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " another."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " also."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " here is."},
    {"prompt": "adibiswat says:", "completion": " one more."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " this is."},
    {"prompt": "adibiswat says:", "completion": " the last message."},
]

gen_dataset_reverse_and_offset_1 = [
    {"prompt": "adibiswat says:", "completion": " this is."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " one more."},
    {"prompt": "adibiswat says:", "completion": " here is."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " also."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " another."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " for the test data."},
    {"prompt": "adibiswat says:", "completion": " pretermined messages."},
    {"prompt": "adibiswat says:", "completion": " writing."},
    {"prompt": "adibiswat says:", "completion": " am."},
    {"prompt": "adibiswat says:", "completion": " i."},
    {"prompt": "adibiswat says:", "completion": " ai tests."},
    {"prompt": "adibiswat says:", "completion": " discord."},
    {"prompt": "adibiswat says:", "completion": " to run."},
    {"prompt": "adibiswat says:", "completion": " test channel."},
    {"prompt": "adibiswat says:", "completion": " a."},
    {"prompt": "adibiswat says:", "completion": " is."},
    {"prompt": "adibiswat says:", "completion": " this."},
]

gen_dataset_reverse_5_max = [
    {"prompt": "adibiswat says:", "completion": " the last message."},
    {"prompt": "adibiswat says:", "completion": " this is."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " one more."},
    {"prompt": "adibiswat says:", "completion": " here is."},
]

gen_dataset_max_5_distributed = [
    {"prompt": "adibiswat says:", "completion": " this."},
    {"prompt": "adibiswat says:", "completion": " discord."},
    {"prompt": "adibiswat says:", "completion": " pretermined messages."},
    {"prompt": "adibiswat says:", "completion": " message."},
    {"prompt": "adibiswat says:", "completion": " message."},
]
